version: "3.5"

services:
  build-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular_app_tpi
    restart: always
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
