export const mockAcciones = [
    {
        "simbolo": "MOCK",
        "ultimoPrecio": 999,
        "variacionPorcentual": 999,
        "apertura": 999,
        "maximo": 999,
        "minimo": 999,
        "ultimoCierre": 999,
        "volumen": 999,
        "cantidadOperaciones": 999,
        "fecha": "2023-09-15T03:00:05.947",
        "mercado": "999",
        "moneda": "999",
        "descripcion": "MOCK ACCION",
        "plazo": "T2",
        "laminaMinima": 999,
        "lote": 999,
        "flashCompra": 999,
        "flashVenta": 999,
        "deleted": false
    },
    {
        "simbolo": "5913",
        "ultimoPrecio": 0,
        "variacionPorcentual": 0,
        "apertura": 0,
        "maximo": 0,
        "minimo": 0,
        "ultimoCierre": 0,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:05.947",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "OCCIDENTAL PETROLEUM CORP. (OXY)",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "7485",
        "ultimoPrecio": 0,
        "variacionPorcentual": 0,
        "apertura": 0,
        "maximo": 0,
        "minimo": 0,
        "ultimoCierre": 0,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:23.703",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "GLOBALSTAR TELECOMMUNICATIONS",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "93729",
        "ultimoPrecio": 0,
        "variacionPorcentual": 0,
        "apertura": 0,
        "maximo": 0,
        "minimo": 0,
        "ultimoCierre": 0,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:07.693",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Spdr Bloomberg Barclays Etf",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "AGRO",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 6000,
            "cantidadVenta": 10,
            "precioVenta": 240,
            "deleted": false
        },
        "ultimoPrecio": 224.75,
        "variacionPorcentual": -2.28,
        "apertura": 231,
        "maximo": 234.75,
        "minimo": 220.25,
        "ultimoCierre": 224.75,
        "volumen": 0,
        "cantidadOperaciones": 652,
        "fecha": "2023-09-15T17:00:05.423",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Agrometal",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "ALUA",
        "puntas": {
            "cantidadCompra": 3,
            "precioCompra": 2000,
            "cantidadVenta": 398,
            "precioVenta": 639.5,
            "deleted": false
        },
        "ultimoPrecio": 639,
        "variacionPorcentual": 4.15,
        "apertura": 619,
        "maximo": 640,
        "minimo": 603,
        "ultimoCierre": 639,
        "volumen": 0,
        "cantidadOperaciones": 4485,
        "fecha": "2023-09-15T17:00:05.43",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Aluar",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "AUSO",
        "puntas": {
            "cantidadCompra": 25,
            "precioCompra": 874,
            "cantidadVenta": 45,
            "precioVenta": 300,
            "deleted": false
        },
        "ultimoPrecio": 983,
        "variacionPorcentual": 0.45,
        "apertura": 996.5,
        "maximo": 1010,
        "minimo": 923,
        "ultimoCierre": 983,
        "volumen": 0,
        "cantidadOperaciones": 42,
        "fecha": "2023-09-15T17:00:05.433",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Autopistas del Sol",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BBAR",
        "puntas": {
            "cantidadCompra": 11,
            "precioCompra": 1085,
            "cantidadVenta": 12,
            "precioVenta": 1358,
            "deleted": false
        },
        "ultimoPrecio": 1198,
        "variacionPorcentual": -1.03,
        "apertura": 1210,
        "maximo": 1226.95,
        "minimo": 1151,
        "ultimoCierre": 1198,
        "volumen": 0,
        "cantidadOperaciones": 534,
        "fecha": "2023-09-15T17:00:06.987",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Bbva",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BHIP",
        "puntas": {
            "cantidadCompra": 4761,
            "precioCompra": 42,
            "cantidadVenta": 700,
            "precioVenta": 42.5,
            "deleted": false
        },
        "ultimoPrecio": 42.45,
        "variacionPorcentual": 1.42,
        "apertura": 42.85,
        "maximo": 42.9,
        "minimo": 41,
        "ultimoCierre": 42.45,
        "volumen": 0,
        "cantidadOperaciones": 79,
        "fecha": "2023-09-15T17:00:05.453",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Banco Hipotecario",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BMA",
        "puntas": {
            "cantidadCompra": 902,
            "precioCompra": 1676.3,
            "cantidadVenta": 100,
            "precioVenta": 1800,
            "deleted": false
        },
        "ultimoPrecio": 1702.85,
        "variacionPorcentual": -1.88,
        "apertura": 1749,
        "maximo": 1780.9,
        "minimo": 1678,
        "ultimoCierre": 1702.85,
        "volumen": 0,
        "cantidadOperaciones": 779,
        "fecha": "2023-09-15T17:00:05.473",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Banco Macro",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BOLT",
        "puntas": {
            "cantidadCompra": 1000000,
            "precioCompra": 0.001,
            "cantidadVenta": 2000,
            "precioVenta": 18.95,
            "deleted": false
        },
        "ultimoPrecio": 17,
        "variacionPorcentual": -2.05,
        "apertura": 17.3,
        "maximo": 17.9,
        "minimo": 15,
        "ultimoCierre": 17,
        "volumen": 0,
        "cantidadOperaciones": 303,
        "fecha": "2023-09-15T17:00:05.48",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Boldt",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BPAT",
        "puntas": {
            "cantidadCompra": 48,
            "precioCompra": 337,
            "cantidadVenta": 222,
            "precioVenta": 344,
            "deleted": false
        },
        "ultimoPrecio": 342,
        "variacionPorcentual": -1.86,
        "apertura": 348.5,
        "maximo": 353,
        "minimo": 336,
        "ultimoCierre": 342,
        "volumen": 0,
        "cantidadOperaciones": 21,
        "fecha": "2023-09-15T17:00:05.487",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Banco Patagonia",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BRIO",
        "ultimoPrecio": 33.5,
        "variacionPorcentual": 0,
        "apertura": 33.85,
        "maximo": 33.85,
        "minimo": 32.6,
        "ultimoCierre": 33.5,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:23.25",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Banco Santander Rio \"B\" Ordinarias 1 V.   Escritur",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "BYMA",
        "puntas": {
            "cantidadCompra": 445,
            "precioCompra": 535.5,
            "cantidadVenta": 555,
            "precioVenta": 541.5,
            "deleted": false
        },
        "ultimoPrecio": 540,
        "variacionPorcentual": 2.96,
        "apertura": 524,
        "maximo": 547,
        "minimo": 500.5,
        "ultimoCierre": 540,
        "volumen": 0,
        "cantidadOperaciones": 1137,
        "fecha": "2023-09-15T17:00:04.527",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Bolsas Y Mercados Argentinos S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CADO",
        "puntas": {
            "cantidadCompra": 3,
            "precioCompra": 249,
            "cantidadVenta": 1000,
            "precioVenta": 255,
            "deleted": false
        },
        "ultimoPrecio": 245,
        "variacionPorcentual": 1.84,
        "apertura": 235,
        "maximo": 249.5,
        "minimo": 234,
        "ultimoCierre": 245,
        "volumen": 0,
        "cantidadOperaciones": 86,
        "fecha": "2023-09-15T17:00:05.49",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Carlos Casado",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CAPX",
        "puntas": {
            "cantidadCompra": 50,
            "precioCompra": 3700,
            "cantidadVenta": 377,
            "precioVenta": 3750,
            "deleted": false
        },
        "ultimoPrecio": 3750,
        "variacionPorcentual": 5.47,
        "apertura": 3450,
        "maximo": 3850,
        "minimo": 3450,
        "ultimoCierre": 3750,
        "volumen": 0,
        "cantidadOperaciones": 115,
        "fecha": "2023-09-15T17:11:58.253",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Capex",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CARC",
        "puntas": {
            "cantidadCompra": 8491,
            "precioCompra": 8.74,
            "cantidadVenta": 28000,
            "precioVenta": 8.84,
            "deleted": false
        },
        "ultimoPrecio": 8.77,
        "variacionPorcentual": -1.35,
        "apertura": 9,
        "maximo": 9.15,
        "minimo": 8.55,
        "ultimoCierre": 8.77,
        "volumen": 0,
        "cantidadOperaciones": 119,
        "fecha": "2023-09-15T17:00:05.5",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Carboclor S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CECO2",
        "puntas": {
            "cantidadCompra": 293,
            "precioCompra": 254.5,
            "cantidadVenta": 2586,
            "precioVenta": 255,
            "deleted": false
        },
        "ultimoPrecio": 255,
        "variacionPorcentual": -0.19,
        "apertura": 265,
        "maximo": 269.5,
        "minimo": 254.5,
        "ultimoCierre": 255,
        "volumen": 0,
        "cantidadOperaciones": 91,
        "fecha": "2023-09-15T17:00:05.507",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Endesa Costanera",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CELU",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 363,
            "cantidadVenta": 3539,
            "precioVenta": 370,
            "deleted": false
        },
        "ultimoPrecio": 373,
        "variacionPorcentual": -3.89,
        "apertura": 400,
        "maximo": 400,
        "minimo": 370,
        "ultimoCierre": 373,
        "volumen": 0,
        "cantidadOperaciones": 37,
        "fecha": "2023-09-15T17:00:05.51",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Celulosa",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CEPU",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 444,
            "cantidadVenta": 21,
            "precioVenta": 506,
            "deleted": false
        },
        "ultimoPrecio": 463.75,
        "variacionPorcentual": -1.88,
        "apertura": 477.3,
        "maximo": 479.9,
        "minimo": 459.6,
        "ultimoCierre": 463.75,
        "volumen": 0,
        "cantidadOperaciones": 1212,
        "fecha": "2023-09-15T17:00:05.513",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Central Puerto Sa",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CGPA2",
        "puntas": {
            "cantidadCompra": 50,
            "precioCompra": 500,
            "cantidadVenta": 150,
            "precioVenta": 501,
            "deleted": false
        },
        "ultimoPrecio": 483,
        "variacionPorcentual": 2.34,
        "apertura": 500,
        "maximo": 509,
        "minimo": 465,
        "ultimoCierre": 483,
        "volumen": 0,
        "cantidadOperaciones": 107,
        "fecha": "2023-09-15T17:00:05.52",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Camuzzi Gas Pampeana",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "COME",
        "puntas": {
            "cantidadCompra": 6,
            "precioCompra": 42,
            "cantidadVenta": 1000,
            "precioVenta": 52.5,
            "deleted": false
        },
        "ultimoPrecio": 47.95,
        "variacionPorcentual": -0.51,
        "apertura": 48.65,
        "maximo": 48.65,
        "minimo": 47.35,
        "ultimoCierre": 47.95,
        "volumen": 0,
        "cantidadOperaciones": 1544,
        "fecha": "2023-09-15T17:00:05.523",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Sociedad Comercial del Plata",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CRE3W",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 303,
            "cantidadVenta": 122,
            "precioVenta": 314,
            "deleted": false
        },
        "ultimoPrecio": 314,
        "variacionPorcentual": -0.39,
        "apertura": 301,
        "maximo": 314.5,
        "minimo": 301,
        "ultimoCierre": 314,
        "volumen": 0,
        "cantidadOperaciones": 31,
        "fecha": "2023-09-15T17:00:08.07",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "WARRANT CRESUD S.A.C.I.F. VTO 08/03/26",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CRES",
        "puntas": {
            "cantidadCompra": 48,
            "precioCompra": 537,
            "cantidadVenta": 183,
            "precioVenta": 539,
            "deleted": false
        },
        "ultimoPrecio": 538.65,
        "variacionPorcentual": -1.03,
        "apertura": 550,
        "maximo": 559.5,
        "minimo": 529,
        "ultimoCierre": 538.65,
        "volumen": 0,
        "cantidadOperaciones": 483,
        "fecha": "2023-09-15T17:00:05.527",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Cresud",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CTIO",
        "puntas": {
            "cantidadCompra": 20,
            "precioCompra": 888,
            "cantidadVenta": 285,
            "precioVenta": 889,
            "deleted": false
        },
        "ultimoPrecio": 881.5,
        "variacionPorcentual": 0.05,
        "apertura": 900,
        "maximo": 900,
        "minimo": 855,
        "ultimoCierre": 881.5,
        "volumen": 0,
        "cantidadOperaciones": 31,
        "fecha": "2023-09-15T17:00:05.537",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Consultatio",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "CVH",
        "puntas": {
            "cantidadCompra": 38,
            "precioCompra": 1831,
            "cantidadVenta": 23,
            "precioVenta": 1849.5,
            "deleted": false
        },
        "ultimoPrecio": 1849.5,
        "variacionPorcentual": 0.35,
        "apertura": 1875,
        "maximo": 1875,
        "minimo": 1807,
        "ultimoCierre": 1849.5,
        "volumen": 0,
        "cantidadOperaciones": 156,
        "fecha": "2023-09-15T17:00:05.677",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Cablevisión Holding S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "DGCU2",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 368,
            "cantidadVenta": 150,
            "precioVenta": 420,
            "deleted": false
        },
        "ultimoPrecio": 381.5,
        "variacionPorcentual": -1.16,
        "apertura": 385,
        "maximo": 390,
        "minimo": 373.5,
        "ultimoCierre": 381.5,
        "volumen": 0,
        "cantidadOperaciones": 65,
        "fecha": "2023-09-15T17:00:05.55",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Distribuidora de Gas Cuyana",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "DOME",
        "puntas": {
            "cantidadCompra": 1927,
            "precioCompra": 19,
            "cantidadVenta": 5000,
            "precioVenta": 20,
            "deleted": false
        },
        "ultimoPrecio": 19.5,
        "variacionPorcentual": -2.56,
        "apertura": 19,
        "maximo": 19,
        "minimo": 19,
        "ultimoCierre": 19.5,
        "volumen": 0,
        "cantidadOperaciones": 2,
        "fecha": "2023-09-15T15:58:46.337",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Suscripción Preferente Domec S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "DYCA",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 240,
            "cantidadVenta": 196,
            "precioVenta": 268,
            "deleted": false
        },
        "ultimoPrecio": 268,
        "variacionPorcentual": 7.73,
        "apertura": 269,
        "maximo": 270,
        "minimo": 263,
        "ultimoCierre": 268,
        "volumen": 0,
        "cantidadOperaciones": 23,
        "fecha": "2023-09-15T15:59:08.23",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Dycasa",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "EDLH",
        "ultimoPrecio": 22.5,
        "variacionPorcentual": 0,
        "apertura": 22.5,
        "maximo": 22.5,
        "minimo": 22.5,
        "ultimoCierre": 22.5,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:07.723",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "EDESAL HOLDING S.A. 1 VOTO $ ESC.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "EDN",
        "puntas": {
            "cantidadCompra": 82,
            "precioCompra": 480,
            "cantidadVenta": 45,
            "precioVenta": 488,
            "deleted": false
        },
        "ultimoPrecio": 486,
        "variacionPorcentual": 0.23,
        "apertura": 475,
        "maximo": 488,
        "minimo": 473,
        "ultimoCierre": 486,
        "volumen": 0,
        "cantidadOperaciones": 713,
        "fecha": "2023-09-15T17:00:05.553",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Edenor",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "EDSH",
        "puntas": {
            "cantidadCompra": 0,
            "precioCompra": 0,
            "cantidadVenta": 121,
            "precioVenta": 471,
            "deleted": false
        },
        "ultimoPrecio": 458,
        "variacionPorcentual": 0,
        "apertura": 458,
        "maximo": 458,
        "minimo": 458,
        "ultimoCierre": 458,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:02.527",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "EDESA HOLDING S.A. 1 VOTO $ ESC.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "ELAP",
        "ultimoPrecio": 0,
        "variacionPorcentual": 0,
        "apertura": 0,
        "maximo": 0,
        "minimo": 0,
        "ultimoCierre": 0,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:05.75",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "EMP.DISTRIB.LA PLATA(EDELAP)-ORD.B 1 V",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "EMAC",
        "ultimoPrecio": 0,
        "variacionPorcentual": 0,
        "apertura": 0,
        "maximo": 0,
        "minimo": 0,
        "ultimoCierre": 0,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:02.303",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "ELECTROMAC",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "ESME",
        "ultimoPrecio": 330,
        "variacionPorcentual": 0,
        "apertura": 330,
        "maximo": 330,
        "minimo": 330,
        "ultimoCierre": 330,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:07.693",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Bodegas Esmeralda",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "FERR",
        "puntas": {
            "cantidadCompra": 200,
            "precioCompra": 44,
            "cantidadVenta": 500,
            "precioVenta": 51.6,
            "deleted": false
        },
        "ultimoPrecio": 51.4,
        "variacionPorcentual": 3.01,
        "apertura": 50.5,
        "maximo": 53.6,
        "minimo": 48.15,
        "ultimoCierre": 51.4,
        "volumen": 0,
        "cantidadOperaciones": 130,
        "fecha": "2023-09-15T17:00:05.557",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Ferrum",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "FIPL",
        "puntas": {
            "cantidadCompra": 1300,
            "precioCompra": 96.1,
            "cantidadVenta": 1300,
            "precioVenta": 100,
            "deleted": false
        },
        "ultimoPrecio": 96.3,
        "variacionPorcentual": -2.24,
        "apertura": 98.4,
        "maximo": 99,
        "minimo": 96,
        "ultimoCierre": 96.3,
        "volumen": 0,
        "cantidadOperaciones": 17,
        "fecha": "2023-09-15T17:00:05.56",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Fiplasto",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GAMI",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 124.25,
            "cantidadVenta": 600,
            "precioVenta": 127.75,
            "deleted": false
        },
        "ultimoPrecio": 127.5,
        "variacionPorcentual": -0.38,
        "apertura": 129.5,
        "maximo": 129.5,
        "minimo": 120,
        "ultimoCierre": 127.5,
        "volumen": 0,
        "cantidadOperaciones": 81,
        "fecha": "2023-09-15T17:00:07.003",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "B-Gaming S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GBAN",
        "puntas": {
            "cantidadCompra": 370,
            "precioCompra": 373,
            "cantidadVenta": 399,
            "precioVenta": 387.5,
            "deleted": false
        },
        "ultimoPrecio": 379,
        "variacionPorcentual": -2.82,
        "apertura": 388.5,
        "maximo": 388.5,
        "minimo": 370,
        "ultimoCierre": 379,
        "volumen": 0,
        "cantidadOperaciones": 18,
        "fecha": "2023-09-15T17:00:05.56",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Gas Natural BAN",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GCDI",
        "puntas": {
            "cantidadCompra": 5026,
            "precioCompra": 15,
            "cantidadVenta": 5928,
            "precioVenta": 15.2,
            "deleted": false
        },
        "ultimoPrecio": 15.2,
        "variacionPorcentual": -0.97,
        "apertura": 15.45,
        "maximo": 16.2,
        "minimo": 14.7,
        "ultimoCierre": 15.2,
        "volumen": 0,
        "cantidadOperaciones": 254,
        "fecha": "2023-09-15T17:00:08.953",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Gcdi S.A. Acciones Ord Esc.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GCLA",
        "puntas": {
            "cantidadCompra": 140,
            "precioCompra": 625.5,
            "cantidadVenta": 100,
            "precioVenta": 639,
            "deleted": false
        },
        "ultimoPrecio": 639.85,
        "variacionPorcentual": -1.18,
        "apertura": 650,
        "maximo": 650,
        "minimo": 619,
        "ultimoCierre": 639.85,
        "volumen": 0,
        "cantidadOperaciones": 65,
        "fecha": "2023-09-15T17:00:05.57",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Grupo Clarín",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GGAL",
        "puntas": {
            "cantidadCompra": 2000,
            "precioCompra": 222,
            "cantidadVenta": 50,
            "precioVenta": 1252,
            "deleted": false
        },
        "ultimoPrecio": 1167.05,
        "variacionPorcentual": -1.92,
        "apertura": 1194,
        "maximo": 1205.95,
        "minimo": 1153.5,
        "ultimoCierre": 1167.05,
        "volumen": 0,
        "cantidadOperaciones": 2976,
        "fecha": "2023-09-15T17:00:05.57",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Grupo Financiero Galicia S.A",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "GRIM",
        "puntas": {
            "cantidadCompra": 192,
            "precioCompra": 519,
            "cantidadVenta": 50,
            "precioVenta": 575,
            "deleted": false
        },
        "ultimoPrecio": 519,
        "variacionPorcentual": 0,
        "apertura": 560,
        "maximo": 560,
        "minimo": 504,
        "ultimoCierre": 519,
        "volumen": 0,
        "cantidadOperaciones": 8,
        "fecha": "2023-09-15T15:00:00.18",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Grimoldi",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "HARG",
        "puntas": {
            "cantidadCompra": 272,
            "precioCompra": 685,
            "cantidadVenta": 428,
            "precioVenta": 693,
            "deleted": false
        },
        "ultimoPrecio": 692,
        "variacionPorcentual": -1,
        "apertura": 701,
        "maximo": 719,
        "minimo": 673.5,
        "ultimoCierre": 692,
        "volumen": 0,
        "cantidadOperaciones": 177,
        "fecha": "2023-09-15T17:00:05.76",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Holcim (Argentina) Ords. 1 Voto",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "HAVA",
        "puntas": {
            "cantidadCompra": 76,
            "precioCompra": 2250,
            "cantidadVenta": 18,
            "precioVenta": 2660,
            "deleted": false
        },
        "ultimoPrecio": 2511.5,
        "variacionPorcentual": 0.74,
        "apertura": 2570.5,
        "maximo": 2570.5,
        "minimo": 2400,
        "ultimoCierre": 2511.5,
        "volumen": 0,
        "cantidadOperaciones": 131,
        "fecha": "2023-09-15T17:00:05.573",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Havanna Holding S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "HULI",
        "ultimoPrecio": 1647,
        "variacionPorcentual": 0,
        "apertura": 1647,
        "maximo": 1647,
        "minimo": 1647,
        "ultimoCierre": 1647,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:08.617",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Hulytego S.A.",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "INAG",
        "ultimoPrecio": 270,
        "variacionPorcentual": 0,
        "apertura": 270,
        "maximo": 270,
        "minimo": 270,
        "ultimoCierre": 270,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:23.25",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Insumos Agroquímicos",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "INTR",
        "puntas": {
            "cantidadCompra": 300,
            "precioCompra": 102,
            "cantidadVenta": 1000,
            "precioVenta": 113,
            "deleted": false
        },
        "ultimoPrecio": 105,
        "variacionPorcentual": -4.4,
        "apertura": 110,
        "maximo": 116,
        "minimo": 103,
        "ultimoCierre": 105,
        "volumen": 0,
        "cantidadOperaciones": 21,
        "fecha": "2023-09-15T17:00:05.583",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Compania Introductora de Bs As",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "INVJ",
        "puntas": {
            "cantidadCompra": 35,
            "precioCompra": 170.5,
            "cantidadVenta": 550,
            "precioVenta": 171,
            "deleted": false
        },
        "ultimoPrecio": 170,
        "variacionPorcentual": -1.15,
        "apertura": 174.75,
        "maximo": 174.75,
        "minimo": 165.5,
        "ultimoCierre": 170,
        "volumen": 0,
        "cantidadOperaciones": 42,
        "fecha": "2023-09-15T17:00:05.587",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Inversora Juramento S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "IRCP",
        "ultimoPrecio": 128.9,
        "variacionPorcentual": 0,
        "apertura": 128,
        "maximo": 129.2,
        "minimo": 124.35,
        "ultimoCierre": 128.9,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:02.543",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Alto Palermo",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "IRS2W",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 315,
            "cantidadVenta": 25,
            "precioVenta": 421.5,
            "deleted": false
        },
        "ultimoPrecio": 368.35,
        "variacionPorcentual": 6.66,
        "apertura": 350,
        "maximo": 369,
        "minimo": 321,
        "ultimoCierre": 368.35,
        "volumen": 0,
        "cantidadOperaciones": 31,
        "fecha": "2023-09-15T17:00:08.12",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "WARRANT INVERSIONES Y REPRESENTACIONES S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "IRSA",
        "puntas": {
            "cantidadCompra": 22,
            "precioCompra": 497,
            "cantidadVenta": 1000,
            "precioVenta": 502.3,
            "deleted": false
        },
        "ultimoPrecio": 499.45,
        "variacionPorcentual": -2.74,
        "apertura": 510,
        "maximo": 510,
        "minimo": 490.5,
        "ultimoCierre": 499.45,
        "volumen": 0,
        "cantidadOperaciones": 637,
        "fecha": "2023-09-15T17:00:05.59",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Irsa",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "LEDE",
        "puntas": {
            "cantidadCompra": 200,
            "precioCompra": 446,
            "cantidadVenta": 1022,
            "precioVenta": 449,
            "deleted": false
        },
        "ultimoPrecio": 449,
        "variacionPorcentual": 2.04,
        "apertura": 430,
        "maximo": 450,
        "minimo": 430,
        "ultimoCierre": 449,
        "volumen": 0,
        "cantidadOperaciones": 102,
        "fecha": "2023-09-15T17:00:05.597",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Ledesma",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "LOMA",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 887.5,
            "cantidadVenta": 58,
            "precioVenta": 890,
            "deleted": false
        },
        "ultimoPrecio": 887.2,
        "variacionPorcentual": -2.22,
        "apertura": 911,
        "maximo": 913,
        "minimo": 882.05,
        "ultimoCierre": 887.2,
        "volumen": 0,
        "cantidadOperaciones": 710,
        "fecha": "2023-09-15T17:00:05.703",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Loma Negra Compañia Industrial Argentina Sa",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "LONG",
        "puntas": {
            "cantidadCompra": 3000,
            "precioCompra": 29.1,
            "cantidadVenta": 2500,
            "precioVenta": 29.95,
            "deleted": false
        },
        "ultimoPrecio": 29.1,
        "variacionPorcentual": 0.34,
        "apertura": 29.5,
        "maximo": 30,
        "minimo": 28,
        "ultimoCierre": 29.1,
        "volumen": 0,
        "cantidadOperaciones": 80,
        "fecha": "2023-09-15T17:00:05.603",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Longvie",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "METR",
        "puntas": {
            "cantidadCompra": 13,
            "precioCompra": 270,
            "cantidadVenta": 1824,
            "precioVenta": 272,
            "deleted": false
        },
        "ultimoPrecio": 270.5,
        "variacionPorcentual": 0.36,
        "apertura": 284,
        "maximo": 284,
        "minimo": 261,
        "ultimoCierre": 270.5,
        "volumen": 0,
        "cantidadOperaciones": 58,
        "fecha": "2023-09-15T17:00:05.607",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Metrogas",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MIRG",
        "puntas": {
            "cantidadCompra": 21,
            "precioCompra": 8700,
            "cantidadVenta": 73,
            "precioVenta": 8729.5,
            "deleted": false
        },
        "ultimoPrecio": 8729,
        "variacionPorcentual": -0.48,
        "apertura": 8770,
        "maximo": 8795,
        "minimo": 8616,
        "ultimoCierre": 8729,
        "volumen": 0,
        "cantidadOperaciones": 183,
        "fecha": "2023-09-15T17:00:05.607",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Mirgor",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MOLA",
        "puntas": {
            "cantidadCompra": 2,
            "precioCompra": 12835,
            "cantidadVenta": 6,
            "precioVenta": 12840,
            "deleted": false
        },
        "ultimoPrecio": 12800,
        "variacionPorcentual": 5.06,
        "apertura": 12185,
        "maximo": 12849,
        "minimo": 12185,
        "ultimoCierre": 12800,
        "volumen": 0,
        "cantidadOperaciones": 132,
        "fecha": "2023-09-15T17:00:04.537",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Molinos Agro S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MOLA5",
        "ultimoPrecio": 3307.5,
        "variacionPorcentual": 0,
        "apertura": 3307.5,
        "maximo": 3307.5,
        "minimo": 3307.5,
        "ultimoCierre": 3307.5,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:00.943",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Molinos Agro S.A 5V $ ESC.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MOLI",
        "puntas": {
            "cantidadCompra": 258,
            "precioCompra": 811,
            "cantidadVenta": 1196,
            "precioVenta": 820,
            "deleted": false
        },
        "ultimoPrecio": 820,
        "variacionPorcentual": -1.44,
        "apertura": 850,
        "maximo": 885,
        "minimo": 800,
        "ultimoCierre": 820,
        "volumen": 0,
        "cantidadOperaciones": 78,
        "fecha": "2023-09-15T17:00:05.61",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Molinos Río De La Plata",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MOLI5",
        "ultimoPrecio": 185,
        "variacionPorcentual": 0,
        "apertura": 185,
        "maximo": 185,
        "minimo": 185,
        "ultimoCierre": 185,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:08.327",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Molinos Río de la Plata 5 Votos",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MORI",
        "puntas": {
            "cantidadCompra": 102,
            "precioCompra": 48,
            "cantidadVenta": 1325,
            "precioVenta": 79,
            "deleted": false
        },
        "ultimoPrecio": 50.7,
        "variacionPorcentual": -0.77,
        "apertura": 51.6,
        "maximo": 52.3,
        "minimo": 49,
        "ultimoCierre": 50.7,
        "volumen": 0,
        "cantidadOperaciones": 153,
        "fecha": "2023-09-15T17:00:05.613",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Morixe Hermanos",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "MTR",
        "puntas": {
            "cantidadCompra": 75,
            "precioCompra": 595,
            "cantidadVenta": 50,
            "precioVenta": 700,
            "deleted": false
        },
        "ultimoPrecio": 660,
        "variacionPorcentual": -1.49,
        "apertura": 690,
        "maximo": 690,
        "minimo": 660,
        "ultimoCierre": 660,
        "volumen": 0,
        "cantidadOperaciones": 46,
        "fecha": "2023-09-15T17:00:07.267",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Matba Rofex S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "OEST",
        "puntas": {
            "cantidadCompra": 56,
            "precioCompra": 339,
            "cantidadVenta": 120,
            "precioVenta": 405,
            "deleted": false
        },
        "ultimoPrecio": 339,
        "variacionPorcentual": 0.43,
        "apertura": 339,
        "maximo": 345,
        "minimo": 325,
        "ultimoCierre": 339,
        "volumen": 0,
        "cantidadOperaciones": 25,
        "fecha": "2023-09-15T17:00:05.613",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Grupo Concesionario del Oeste",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "PAMP",
        "puntas": {
            "cantidadCompra": 11,
            "precioCompra": 1120,
            "cantidadVenta": 5,
            "precioVenta": 1385,
            "deleted": false
        },
        "ultimoPrecio": 1198.95,
        "variacionPorcentual": -2.51,
        "apertura": 1232,
        "maximo": 1240,
        "minimo": 1191,
        "ultimoCierre": 1198.95,
        "volumen": 0,
        "cantidadOperaciones": 4449,
        "fecha": "2023-09-15T17:00:05.617",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Pampa Energía",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "PATA",
        "puntas": {
            "cantidadCompra": 100,
            "precioCompra": 328.5,
            "cantidadVenta": 219,
            "precioVenta": 370,
            "deleted": false
        },
        "ultimoPrecio": 334,
        "variacionPorcentual": -0.43,
        "apertura": 346,
        "maximo": 346,
        "minimo": 321,
        "ultimoCierre": 334,
        "volumen": 0,
        "cantidadOperaciones": 61,
        "fecha": "2023-09-15T17:00:05.63",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Imp. y Exportadora de la Patagonia",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "PGR",
        "ultimoPrecio": 24.6,
        "variacionPorcentual": 0,
        "apertura": 25.8,
        "maximo": 25.8,
        "minimo": 24.3,
        "ultimoCierre": 24.6,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:01.947",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Phoenix Global Resources Plc",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "POLL",
        "puntas": {
            "cantidadCompra": 0,
            "precioCompra": 0,
            "cantidadVenta": 752,
            "precioVenta": 75,
            "deleted": false
        },
        "ultimoPrecio": 77,
        "variacionPorcentual": 0,
        "apertura": 77,
        "maximo": 77,
        "minimo": 77,
        "ultimoCierre": 77,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:05.783",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Polledo",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "REGE",
        "ultimoPrecio": 650,
        "variacionPorcentual": 0,
        "apertura": 650,
        "maximo": 650,
        "minimo": 650,
        "ultimoCierre": 650,
        "volumen": 0,
        "cantidadOperaciones": 0,
        "fecha": "2023-09-15T03:00:01.913",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "García Regera",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "RICH",
        "puntas": {
            "cantidadCompra": 3,
            "precioCompra": 535,
            "cantidadVenta": 26,
            "precioVenta": 541,
            "deleted": false
        },
        "ultimoPrecio": 544,
        "variacionPorcentual": -0.72,
        "apertura": 568.5,
        "maximo": 568.5,
        "minimo": 525.5,
        "ultimoCierre": 544,
        "volumen": 0,
        "cantidadOperaciones": 106,
        "fecha": "2023-09-15T17:00:05.743",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Laboratorios Richmond S.A.C.I.F.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "RIGO",
        "puntas": {
            "cantidadCompra": 0,
            "precioCompra": 0,
            "cantidadVenta": 1163,
            "precioVenta": 750,
            "deleted": false
        },
        "ultimoPrecio": 750,
        "variacionPorcentual": 0,
        "apertura": 750,
        "maximo": 750,
        "minimo": 750,
        "ultimoCierre": 750,
        "volumen": 0,
        "cantidadOperaciones": 1,
        "fecha": "2023-09-15T15:00:00.183",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Rigolleau",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "SAMI",
        "puntas": {
            "cantidadCompra": 163,
            "precioCompra": 427.5,
            "cantidadVenta": 124,
            "precioVenta": 430,
            "deleted": false
        },
        "ultimoPrecio": 431,
        "variacionPorcentual": -2.05,
        "apertura": 438.5,
        "maximo": 442,
        "minimo": 425,
        "ultimoCierre": 431,
        "volumen": 0,
        "cantidadOperaciones": 198,
        "fecha": "2023-09-15T17:00:05.64",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "San Miguel",
        "plazo": "T2",
        "laminaMinima": 0,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "SEMI",
        "puntas": {
            "cantidadCompra": 1125,
            "precioCompra": 86.7,
            "cantidadVenta": 5700,
            "precioVenta": 100,
            "deleted": false
        },
        "ultimoPrecio": 88.6,
        "variacionPorcentual": -3.88,
        "apertura": 92,
        "maximo": 93,
        "minimo": 86.7,
        "ultimoCierre": 88.6,
        "volumen": 0,
        "cantidadOperaciones": 130,
        "fecha": "2023-09-15T17:00:05.653",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Molinos Juan Semino",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "SUPV",
        "puntas": {
            "cantidadCompra": 130,
            "precioCompra": 384,
            "cantidadVenta": 1994,
            "precioVenta": 386.5,
            "deleted": false
        },
        "ultimoPrecio": 385.85,
        "variacionPorcentual": -1.36,
        "apertura": 399.95,
        "maximo": 399.95,
        "minimo": 375,
        "ultimoCierre": 385.85,
        "volumen": 0,
        "cantidadOperaciones": 730,
        "fecha": "2023-09-15T17:00:05.657",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Grupo Supervielle S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "TECO2",
        "puntas": {
            "cantidadCompra": 112,
            "precioCompra": 769,
            "cantidadVenta": 1715,
            "precioVenta": 770,
            "deleted": false
        },
        "ultimoPrecio": 769.25,
        "variacionPorcentual": -3.21,
        "apertura": 796,
        "maximo": 812.95,
        "minimo": 761,
        "ultimoCierre": 769.25,
        "volumen": 0,
        "cantidadOperaciones": 675,
        "fecha": "2023-09-15T17:00:05.663",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Telecom Argentina",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "TGNO4",
        "puntas": {
            "cantidadCompra": 16,
            "precioCompra": 796,
            "cantidadVenta": 13,
            "precioVenta": 1000,
            "deleted": false
        },
        "ultimoPrecio": 803,
        "variacionPorcentual": -1.6,
        "apertura": 806.5,
        "maximo": 827,
        "minimo": 773,
        "ultimoCierre": 803,
        "volumen": 0,
        "cantidadOperaciones": 1363,
        "fecha": "2023-09-15T17:00:05.667",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Transportadora Gas del Norte",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "TGSU2",
        "puntas": {
            "cantidadCompra": 2,
            "precioCompra": 1660,
            "cantidadVenta": 350,
            "precioVenta": 1875,
            "deleted": false
        },
        "ultimoPrecio": 1681.8,
        "variacionPorcentual": -3.94,
        "apertura": 1800,
        "maximo": 1800,
        "minimo": 1678,
        "ultimoCierre": 1681.8,
        "volumen": 0,
        "cantidadOperaciones": 1170,
        "fecha": "2023-09-15T17:00:05.67",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Transportadora Gas del Sur",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "TRAN",
        "puntas": {
            "cantidadCompra": 34279,
            "precioCompra": 427,
            "cantidadVenta": 10446,
            "precioVenta": 430,
            "deleted": false
        },
        "ultimoPrecio": 428.5,
        "variacionPorcentual": -0.58,
        "apertura": 442,
        "maximo": 442,
        "minimo": 415,
        "ultimoCierre": 428.5,
        "volumen": 0,
        "cantidadOperaciones": 553,
        "fecha": "2023-09-15T17:00:05.673",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Transener",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "TXAR",
        "puntas": {
            "cantidadCompra": 2568,
            "precioCompra": 593,
            "cantidadVenta": 368,
            "precioVenta": 597,
            "deleted": false
        },
        "ultimoPrecio": 595,
        "variacionPorcentual": 5.75,
        "apertura": 579,
        "maximo": 599,
        "minimo": 550.5,
        "ultimoCierre": 595,
        "volumen": 0,
        "cantidadOperaciones": 2453,
        "fecha": "2023-09-15T17:00:05.773",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Ternium Argentina Sa",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "VALO",
        "puntas": {
            "cantidadCompra": 2,
            "precioCompra": 112,
            "cantidadVenta": 51,
            "precioVenta": 150,
            "deleted": false
        },
        "ultimoPrecio": 129,
        "variacionPorcentual": 2.77,
        "apertura": 127,
        "maximo": 130,
        "minimo": 124.25,
        "ultimoCierre": 129,
        "volumen": 0,
        "cantidadOperaciones": 1029,
        "fecha": "2023-09-15T17:00:08.123",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "Banco de Valores S.A.",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    },
    {
        "simbolo": "YPFD",
        "puntas": {
            "cantidadCompra": 195,
            "precioCompra": 9426,
            "cantidadVenta": 547,
            "precioVenta": 9455,
            "deleted": false
        },
        "ultimoPrecio": 9415.5,
        "variacionPorcentual": -2.3,
        "apertura": 9850,
        "maximo": 9850,
        "minimo": 9340.55,
        "ultimoCierre": 9415.5,
        "volumen": 0,
        "cantidadOperaciones": 3242,
        "fecha": "2023-09-15T17:00:05.677",
        "mercado": "1",
        "moneda": "1",
        "descripcion": "YPF",
        "plazo": "T2",
        "laminaMinima": 1,
        "lote": 1,
        "flashCompra": 0,
        "flashVenta": 0,
        "deleted": false
    }
]